import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Section from "../PageRow/section";
import SectionRow from "../PageRow/SectionRow";
import Contact from "../PageRow/SectionContact";
import Main from "../PageRow/main";
import Header from "../PageRow/Header";
import RevealSimple from "../PageRow/RevealSimple";
import ShowReklama from "../PageRow/reklamaShow";
import "@fontsource/montserrat";
import "@fontsource/montserrat/400-italic.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} style={{ backgroundColor: " #0f2330" }}>
        <div className="wrapper">
          <ShowReklama durationMs={8000} oncePerSession={true} />
          <RevealSimple />
          <Header />
          <Main />
          <Section />
          <SectionRow />
          <Contact />
          {children}
        </div>
      </body>
    </html>
  );
}
